#!/usr/bin/env python
# Launch Zim with the gnomeshellsearch plugin.

import os

if __name__ == "__main__":
    os.execvp("zim", ["zim", "--plugin", "gnomeshellsearch"])

# TODO: with some folder reorganization, this script could detect when
# it is being run from within the source tree, and tell zim to use this
# dir's plugin code (os.execvpe() & overriding $XDG_DATA_HOME) instead
# of the installed copy. This would be nice for local testing.
